### ISSUE TITLE
Need to upload the sound sample data promised in the paper

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/ProtoSound#3]
In the CHI paper, we say:

> To support training for these difficult-to-produce sounds, ProtoSound contains samples of 10 sound categories preferred by DHH people [5,26] (e.g., fire/smoke alarms, babies crying, sirens, bird chirps), procured from a high-quality online library, FreeSound. These sound samples were manually cleaned (removing noise, deleting silences) by three hearing authors and are available in ProtoSound’s repository. 

However, I don't see these sounds anywhere in our repo. We need a data folder, right?

**Comment by higherdefender** [comment]
README now points to the sound sample data https://github.com/makeabilitylab/ProtoSound/commit/72584b43ea1e3b3a8659ddb5918295328527abb4

**Comment by higherdefender** [comment]
README now points to the sound sample data. Commit: https://github.com/makeabilitylab/ProtoSound/commit/72584b43ea1e3b3a8659ddb5918295328527abb4
